### ISSUE TITLE
./prechelt/learn-from-failure.md

### ISSUE THREAD

**Issue by timm** [ds4se/chapters#68] opened 2015-10-16 05:55 UTC
After review, relabel to 'reviewTwo'. After second review, relabel to 'EditorsComment'.

**Comment by alexorso** [comment] 2015-12-17 06:21
# Review

## Title of chapter

The White-Shirt Effect, or: Learning from Expectations that Failed

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/prechelt/learn-from-failure.md

## Message?

What is the chapter's  clear and approachable take away message?

I see two:
- Learn something when your hypotheses are not confirmed by the data.
- Think about your hypotheses before investing a great deal of effort into testing them.

## Accessible?

Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?
How can it be made more accessible to generalist?

The chapter is targeted to data scientists, but it is nevertheless accessible and does not require any particular knowledge. The only technical term used is "causational model", I believe, whose meaning should be clear to most readers. (By the way, shouldn't it be "causal model"?)

## Size?

Is the chapter the right length?
Should anything missing be added?
Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?
What are the aspects of the chapter that authors  SHOULD  change?

I find the initial example a bit long, especially with respect to the "Practical Advice" section. Although I don't feel particularly strong about it, I believe that the example could be made more concise without losing much and that expanding the final section a bit (and possibly merging it with the previous section--see below) would benefit the chapter.

There seems to be a little bit of a disconnect between the first two sections ("A Story" and "The Right Reaction") and the third one ("Practical Advice"). The former are about what to do when your hypotheses are not confirmed by your study, which is also what the title expresses, whereas I read the latter mainly as a suggestion to think about your hypothesis (and possibly break them down in easier-to-test sub-hypotheses) before investing a great deal of effort into testing them. In fact, the third chapter seems to suggest that the "right reaction" to an unsuccessful study is often Option 1 (cut your losses), rather than Option 2 (keep looking). Maybe I am missing something here, but I feel like Sections 2 and 3 could be combined to either send a more coherent message or better integrate the different ones.

Minor stuff:
- "white-shirt complicance rate": "compliance"?
- Some punctuation issues.

## Gotta Mantra?

We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here.

I think the title is pretty catchy. Maybe I would remove the "or" and shorten it: "The White-Shirt Effect: Learning from Failed Expectations"

## Best Points

What are the best points of the chapter that the authors should NOT change?

I liked the use of an opening story to motivate and set the context for the rest of the chapter.

**Comment by tzimmermsr** [comment] 2015-12-22 23:27
## Title of chapter

The White-Shirt Effect

## URL to the chapter

https://github.com/ds4se/chapters/blob/master/prechelt/learn-from-failure.md

## Message?

_What is the chapter's  clear and approachable take away message?_
Have a Causational Model before you do anything

## Accessible?

_Is the chapters written for a generalist audience (no excessive use of technical terminology) with a minimum of diagrams and references?_
_How can it be made more accessible to generalist?_

The chapter is written for a generalist audience.

The "having a PhD in empirical software engineering" excludes a large number of the readership.

## Size?

_Is the chapter the right length?_
_Should anything missing be added?_
_Can anything superfluous be removed (e.g. by deleting some section that does not work so well or  by using less jargon, less formulae, lees diagrams, less references).?_
_What are the aspects of the chapter that authors  SHOULD  change?_

The white-shirt effect example works great for the section "Story" (please keep it there!). However, I felt that It worked less for the section "The Right Reaction" because the example is so silly; its highly likely that the person had no rational idea of causation in the first place. (Unless you expect that the majority of the readers will believe in a white-shirt effect.) Maybe use a more rational example for the "Right Approach" section.

Improve the connection of Practical Advice to the rest of the chapter.

obivious => obvious

## Gotta Mantra?

_We encouraged (but did not require) the chapter title to be a mantra or something cute/catchy, i.e., some slogan reflecting best practice for data science for SE?  If you have suggestion for a better title, please put them here._

Fantastic title

## Best Points

_What are the best points of the chapter that the authors should NOT change?_

The white-shirt effect is awesome.

**Comment by tzimmermsr** [comment] 2015-12-23 20:16
@prechelt Please take a look at the reviews and prepare a new version of your paper by January 13. In particular focus on (1) improving the connection between the first two sections and the third one and optionally (2) consider using a better example for the section 2.

**Comment by prechelt** [comment] 2016-01-05 11:33
Alex, Tom,

thanks for your comments.
Using a different example for Section 2 was not possible (it would make the chapter burst), but connecting Section 3 better to Section 2 worked out nicely.
I also found a few more typos and improved some formulations.
I have checked in my reworked version and have relabeled the issue to "5.AuthorHasRevised".

**Comment by tzimmermsr** [comment] 2016-02-03 22:37
Thanks @prechelt for the revisions. Looks good to me.

http://gawker.com/5848754/steve-jobs-on-why-he-wore-turtlenecks

**Closed as completed** 2016-02-07 22:34 UTC
Labels: 5.AuthorHasRevised
